# adapted from https://stackoverflow.com/questions/62009507/buildspec-yml-file-for-spring-boot-project
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn -Pprod package -X
  post_build:
    commands:
    - echo Build completed on `date`
    - mv target/PhilsWebsite-0.0.1-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
#  - .ebextensions/**/*
